### PR TITLE
Add exporting of saved request folders

### PR DESCRIPTION
**Pull request by robhor**
Addressing #65, this PR enables folders of saved requests to be exported and imported again.

### CODE REVIEW

**Comment by mmattozzi** [comment]
This looks awesome... I'll review and get this merged soon! Thanks!

**Comment by mmattozzi** [comment]
Thanks for the much needed fix, I just checked it out and ran it and I noticed only one issue. If I export a folder and then import that folder, the list of saved requests is in an NSArray rather than an NSMutableArray so once it is imported, attempting to add any additional items to that folder will result in a ```2015-12-05 13:33:55.178 CocoaRestClient[6910:1779091] -[__NSArrayI insertObject:atIndex:]: unrecognized selector sent to instance 0x6100000281a0```.

**Comment by robhor** [comment]
Thanks, I updated the pull request!

The problem was that the `@property(nonatomic, copy) NSMutableArray *contents;` declaration caused an immutable copy to be created when setting the `contents` property of a `CRCSavedRequestsFolder`.
I added a custom setter for the `contents` property that instead creates a mutable copy!

**Comment by acanewby** [comment]
Hi chaps.  

First off:  Rob, Thanks very much for stepping up.  Really looking forward to seeing your work on this item.  However, I pulled your code down and I see three compile errors in ExportRequestsController.m.

They are all the same: "Expected a type".

I attached an XCode screenshot so you can see.  Is this a mistake on my part?  I have programmed a lot of environments but not XCode/Objective-C so I'm not sure whether I've made a rookie mistake.  (But I did do the pod install piece.)
exportrequestscontroller-build-failed

**Comment by robhor** [comment]
> I pulled your code down and I see three compile errors in ExportRequestsController.m.

What version of Xcode are you using? Nullability annotations for Objective-C are available starting in Xcode 6.3, so maybe try removing those `nullable` keywords!

**Comment by acanewby** [comment]
That might be the issue.  I'm on OS X 10.9.5, XCode 6.0.1.  Rather than muck around with your code, I'll try and update XCode.

**Comment by acanewby** [comment]
Nope - last available XCode on 10.9.5 is 6.2.  I'll bite the bullet, upgrade and try again ...  (but perhaps Matt will have released a new build by then ... )

**Comment by Relequestual** [comment]
What are the requirements to form a new release?
Found this bug myself, found it already reported, and a merged pull request. How refreshing! =]

**Comment by mmattozzi** [comment]
Yeah, I was already thinking this bugfix justifies a new release... I just need to get a few minutes to sit down and create it.

**Comment by Relequestual** [comment]
Sure! Totally understand.

**Comment by acanewby** [comment]
Woo hoo!  Santa's coming early!


---------------------------
Adrian Newby
acanewby@yahoo.com
+1 310 293 2448
+44 7933 573147

**Pull request merged**
