### PR TITLE
System Tint implemented in main views, removed lots of UI glue code and replaced it with bindings, added persistence for raw input and syntax highlight settings, clean up, fixes, etc...

### PR DESCRIPTION
**Pull request by DiegoMax**
Hi, i just implemented system-wide tint color on the main window, i have also added exceptions to allow for non HTTPS requests on newer versions of OSX and fixed a few warnings.
Could you consider merging this ? Thanks!

### CODE REVIEW

**Comment by DiegoMax** [comment]
Hello, i have added a few more things regarding persistence of raw input, syntax highlight, etc. And also removed a lot of glue code and replaced it with bindings. You can see more details on the commit messages. Please consider merging this, thanks!

**Comment by grzegorz-dubicki** [comment]
+1

**Comment by mmattozzi** [comment]
This looks great, thanks! I'll probably roll a new release after I move Sparkle to cocoapods and update it to the latest version.

**Comment by DiegoMax** [comment]
Im doing some last minute UI adjustments, thanks for the merge, i will do an extra commit in a few mins to fix some UI discrepancies that i didnt notice before.

**Comment by mmattozzi** [comment]
Interesting... when I ran your PR, everything worked fine... after my merge I had to update my base SDK to Latest OS X (which is fine, it's hard to support these older versions anyway) -- but after I did that, all http URLs are still failing to open. What was the property you changed that should have corrected that?

**Comment by DiegoMax** [comment]
Its this one on the info.plist
https://www.dropbox.com/s/jll0hwj9jjet98r/Screenshot%202016-03-09%2010.17.13.jpg?dl=0

**Comment by DiegoMax** [comment]
Were u able to make it work @mmattozzi ?

**Comment by mmattozzi** [comment]
Sorry to leave you hanging... had to go catch the train to head to work. I'll check it out tonight or tomorrow. Thanks for all the updates today...

**Comment by DiegoMax** [comment]
no prob! let me know if u have any issues, cheers!

**Pull request merged**
