### PR TITLE
Fixes leftover issues from the conversion to Auto Layout. Complete UI re-organization and cleaning. Implemented DMSlidingTabView. Many many more things.

### PR DESCRIPTION
**Pull request by DiegoMax**
Sorry about the double PR, this one includes some leftover fixes, alignments, and stuff that i was finishing. Now everything should look ok again.

### CODE REVIEW

**Comment by DiegoMax** [comment]
Ok, so this is the good one.
screenshot 2016-03-10 01 08 38

**Comment by mmattozzi** [comment]
Wow! Looks cool...

**Comment by DiegoMax** [comment]
Let me know if you think that we could merge this, or if you don't like the idea, thanks!

**Comment by mmattozzi** [comment]
I think it's a good idea... I'll be playing around with it tonight and will
probably merge or ask some questions.

**Comment by DiegoMax** [comment]
I know auto-layout can be a bitch at first sight (i have been there). Just keep in mind that every section of the app (every tab) is now a separate view on the main XIB, which makes it much easier to manage.
The views / tabs are instantiated in applicationDidFinishLaunching(), and other than that, all the magic happens inside DMSlidingTabView which is a really simple class that i wrote to deal with the UI of this app. I think we gained a lot of screen real estate, and also, we gained on peace of mind when the time to update the UI for a tab comes.
After using this app for so much time, i finally had some time to give something back. Thank you for writing this tool!
Diego.

**Comment by mmattozzi** [comment]
Really great job... excited to start using it! I'll prepare a new release soon...

**Comment by DiegoMax** [comment]
Thanks!!!!!. Is there any way i can contact you with some questions or should i use the issue tracker ?

**Pull request merged**
